### ISSUE TITLE
[DOCS] 

### ISSUE THREAD

**Issue by parus-cristatus** [Toloka/toloka-kit#107]
### Problem description

1. Create a pool via UI
2. Upload tasks with create_tasks via Kit
3. Pool can't be launched because there's no mixer and no suites are created

### Documentation links

https://toloka.ai/en/docs/toloka-kit/reference/toloka.client.TolokaClient.create_tasks

### Potential fix suggestion

Here mixer_config is mentioned: https://toloka.ai/en/docs/api/concepts/tasks
Maybe add smth like this

**Comment by Pocoder** [comment]
Mention that mixer_config must be set was added in the [docs](https://toloka.ai/en/docs/toloka-kit/reference/toloka.client.TolokaClient.create_tasks).
