### ISSUE TITLE
dynamic answer processing feature

### ISSUE THREAD

**Issue by loompa** [Toloka/toloka-kit#19]
Hi! I think it would be great to have an opportunity to process annotation results on-the-fly, what do you think? Possible use cases are:

- if the annotator makes a lot of mistakes on golden sets we can show him feedback on what he is doing bad and where he has to focus his attention
- ban him immediately if he is still doing bad annotation and resend this task in pool

**Comment by Losik** [comment]
Hi! We are planning on adding webhooks support in our next Toloka-Kit release. This functionality will allow you to react to individual events as soon as they happen.

**Comment by Losik** [comment]
Hello again, methods for working with Web-Hooks are out with version 0.1.8. You can use them for now.
We are also planning to make more user-friendly interfaces around online assignments processing by the end of July.

**Comment by Losik** [comment]
Hi, with Toloka-Kit v0.1.13 we've introduced a new `toloka.streaming` submodule, allowing users to subscribe to Toloka events right from a jupyter notebook. Usage examples will be available soon

**Comment by Losik** [comment]
@loompa, hi, you can see an example of streamed assignments processing in https://github.com/Toloka/toloka-kit/tree/main/examples/6.streaming_pipelines
