### ISSUE TITLE
Image Segmentation example is in fact Object Detection

### ISSUE THREAD

**Issue by pilot7747** [Toloka/toloka-kit#21]
[This example](https://github.com/Toloka/toloka-kit/blob/main/examples/image_segmentation/image_segmentation.ipynb) says that it's an image segmentation project. However, image segmentation means that you can select an arbitrary area of an image. In fact, in this project, performers only draw bounding boxes, so it's an **object detection** task.

Please fix this in the title and the notebook.

**Comment by Losik** [comment]
Done https://github.com/Toloka/toloka-kit/tree/main/examples/1.computer_vision/object_detection
