### ISSUE TITLE
Aggregation issue

### ISSUE THREAD

**Issue by K-Mike** [Toloka/toloka-kit#29]
I try to aggregate result from my pool with code:

```
    aggregation_operation = toloka_client.aggregate_solutions_by_pool(
        type=AggregatedSolutionType.DAWID_SKENE,
        pool_id=pool_id,
        fields=[toloka.aggregation.PoolAggregatedSolutionRequest.Field(name=field_name)]
    )
    aggregation_operation = toloka_client.wait_operation(aggregation_operation)
    print('Results aggregated')

    aggregation_result = toloka_client.find_aggregated_solutions(aggregation_operation.id, limit=100_000)
    verification_results = aggregation_result.items
    while aggregation_result.has_more:
        aggregation_result = toloka_client.find_aggregated_solutions(
            aggregation_operation.id,
            task_id_gt=aggregation_result.items[len(aggregation_result.items) - 1].task_id,
        )
        verification_results = verification_results + aggregation_result.items
```

But I get only 3660 task aggregation, but there are 5000 tasks, if I use online version, it works correct (on different pools the same story).

why does it happen? and how to fix it?
Maybe better use API without the KIT?
Thank you for your answer.

**Comment by Losik** [comment]
Hello, it seems like your code does not use sorting by `task_id` while traversing `find_assignments` result paging. This may results in `aggregation_result.items[len(aggregation_result.items) - 1].task_id` being an arbitrary `task_id` and breaks the traversion logic.

The easiest way to traverse all assignments is to use `get_assignments` method, which does all the tedious work for you https://yandex.com/dev/toloka/toloka-kit/doc/reference/toloka.client.TolokaClient.get_assignments.html
