### ISSUE TITLE
Is it possible to delete task from pool? 

### ISSUE THREAD

**Issue by Developertexteditor** [Toloka/toloka-kit#40]
Hi,

Since there is no way to set overlap to 0 is it possible to delete task from pool via api as it is allowed in web version of Toloka? 

<img width="767" alt="Screenshot 2021-09-15 at 20 18 50" src="https://user-images.githubusercontent.com/38893281/133479729-e21d5e88-ada6-43b9-8516-bea09e2399fd.png">

**Comment by Losik** [comment]
Hello, @Developertexteditor!
Currently you cannot delete a task from API, but you can set its overlap to 0 with `toloka_client.patch_task_overlap_or_min(task_id, overlap=0)`.  
Yes, you cannot create a task with a 0 overlap but you can patch it afterwards

**Comment by Developertexteditor** [comment]
Wow, I tried `.patch_task()` but it told me there is no way to go under 1 overlap. 
Thanks! Closing issue.
