### ISSUE TITLE
Improvement 6.streaming_pipelines example

### ISSUE THREAD

**Issue by Kucev** [Toloka/toloka-kit#51]
Thanks for a very helpful example [6.streaming_pipelines](https://github.com/Toloka/toloka-kit/tree/main/examples/6.streaming_pipelines). Using this example, I figured out how to work with streaming pipelines.

The only point that I think is worth improving:

The HandleSbS class has a line `self.scores_by_image[image] = scores.sort_values(ascending=False)`, that stores the final markup responses. At the same time, after the end of the pipeline, the result of the final marking is not displayed anywhere. It would be great if the notebook had a final cell in which the markup result was displayed.

**Comment by vlad-mois** [comment]
Hello, Roman! Thank you for your feedback. It's really worth displaying the results there. I will add this section soon.

**Comment by vlad-mois** [comment]
Done.
