### ISSUE TITLE
[Feature]: Add parameter 'infinite_overlap': True for control tasks 

### ISSUE THREAD

**Issue by parus-cristatus** [Toloka/toloka-kit#62]
Hey, it'd be great to add infinite overlap for control tasks in this example: https://toloka.ai/en/docs/toloka-kit/reference/toloka.client.TolokaClient.create_tasks and somehow highlight that it's important

**Comment by Pocoder** [comment]
I have added mention that infinite overlap could be useful for control tasks in [this pr](https://github.com/Toloka/toloka-kit/pull/104)
