### ISSUE TITLE
[Question] Pool type

### ISSUE THREAD

**Issue by parus-cristatus** [Toloka/toloka-kit#76]
Hii, is it somehow possible to set a pool type in Toloka Kit?
Like in this example with exam pool: https://colab.research.google.com/github/oleg-cat/blood-test/blob/main/blood-test.ipynb ?
As far as I can see from the Docs - there can be only 2 types: regular and training. Though it's possible to set in the UI

**Comment by alexdrydew** [comment]
Hi! Thank you for being interested in toloka-kit.
Currently, pool subtypes are unsupported by the Toloka API. Setting a pool with the needed subtype (e.g., exam pool) in the UI and cloning it whenever you need to create such a pool using API might work as a workaround (though I can't say it is a good solution). Sorry for the inconvenience.

**Comment by parus-cristatus** [comment]
Got it, thanks for quick answer and Colab examples as well :)
